Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Events\\UserLoggedIn",
            "name": "UserLoggedIn",
            "summary": "Class\u0020UserLoggedIn",
            "url": "classes/App-Events-UserLoggedIn.html"
        },                {
            "fqsen": "\\App\\Events\\UserLoggedIn\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020event\u0020instance.",
            "url": "classes/App-Events-UserLoggedIn.html#method___construct"
        },                {
            "fqsen": "\\App\\Events\\UserLoggedIn\u003A\u003A\u0024user",
            "name": "user",
            "summary": "The\u0020user\u0020instance.",
            "url": "classes/App-Events-UserLoggedIn.html#property_user"
        },                {
            "fqsen": "\\App\\Events\\UserLoggedIn\u003A\u003A\u0024ipAddress",
            "name": "ipAddress",
            "summary": "The\u0020IP\u0020address\u0020of\u0020the\u0020user.",
            "url": "classes/App-Events-UserLoggedIn.html#property_ipAddress"
        },                {
            "fqsen": "\\App\\Events\\UserLoggedIn\u003A\u003A\u0024loginTime",
            "name": "loginTime",
            "summary": "The\u0020login\u0020timestamp.",
            "url": "classes/App-Events-UserLoggedIn.html#property_loginTime"
        },                {
            "fqsen": "\\App\\Exceptions\\VendorAlreadyRegisteredException",
            "name": "VendorAlreadyRegisteredException",
            "summary": "",
            "url": "classes/App-Exceptions-VendorAlreadyRegisteredException.html"
        },                {
            "fqsen": "\\App\\Exceptions\\VendorAlreadyRegisteredException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "VendorAlreadyRegisteredException\u0020constructor.",
            "url": "classes/App-Exceptions-VendorAlreadyRegisteredException.html#method___construct"
        },                {
            "fqsen": "\\App\\Exceptions\\VendorAlreadyRegisteredException\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Render\u0020the\u0020exception\u0020as\u0020a\u0020JSON\u0020response\u0020using\u0020ResponseHelper.",
            "url": "classes/App-Exceptions-VendorAlreadyRegisteredException.html#method_render"
        },                {
            "fqsen": "\\App\\Helpers\\ResponseHelper",
            "name": "ResponseHelper",
            "summary": "Class\u0020ResponseHelper\nProvides\u0020standardized\u0020JSON\u0020response\u0020formatting\u0020for\u0020the\u0020application.",
            "url": "classes/App-Helpers-ResponseHelper.html"
        },                {
            "fqsen": "\\App\\Helpers\\ResponseHelper\u003A\u003Asuccess\u0028\u0029",
            "name": "success",
            "summary": "Generate\u0020a\u0020successful\u0020JSON\u0020response.",
            "url": "classes/App-Helpers-ResponseHelper.html#method_success"
        },                {
            "fqsen": "\\App\\Helpers\\ResponseHelper\u003A\u003Aerror\u0028\u0029",
            "name": "error",
            "summary": "Generate\u0020an\u0020error\u0020JSON\u0020response.",
            "url": "classes/App-Helpers-ResponseHelper.html#method_error"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth\\LoginController",
            "name": "LoginController",
            "summary": "Class\u0020LoginController",
            "url": "classes/App-Http-Controllers-API-V1-Auth-LoginController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth\\LoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "LoginController\u0020constructor.",
            "url": "classes/App-Http-Controllers-API-V1-Auth-LoginController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth\\LoginController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Handle\u0020the\u0020login\u0020request.",
            "url": "classes/App-Http-Controllers-API-V1-Auth-LoginController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth\\LoginController\u003A\u003A\u0024authService",
            "name": "authService",
            "summary": "",
            "url": "classes/App-Http-Controllers-API-V1-Auth-LoginController.html#property_authService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth\\RegisterController",
            "name": "RegisterController",
            "summary": "Class\u0020RegisterController",
            "url": "classes/App-Http-Controllers-API-V1-Auth-RegisterController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth\\RegisterController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "RegisterController\u0020constructor.",
            "url": "classes/App-Http-Controllers-API-V1-Auth-RegisterController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth\\RegisterController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020a\u0020new\u0020user.",
            "url": "classes/App-Http-Controllers-API-V1-Auth-RegisterController.html#method_register"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth\\RegisterController\u003A\u003A\u0024authService",
            "name": "authService",
            "summary": "",
            "url": "classes/App-Http-Controllers-API-V1-Auth-RegisterController.html#property_authService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Vendor\\VendorRegisterController",
            "name": "VendorRegisterController",
            "summary": "",
            "url": "classes/App-Http-Controllers-API-V1-Vendor-VendorRegisterController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Vendor\\VendorRegisterController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "RegisterController\u0020constructor.",
            "url": "classes/App-Http-Controllers-API-V1-Vendor-VendorRegisterController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Vendor\\VendorRegisterController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Handle\u0020the\u0020registration\u0020of\u0020a\u0020new\u0020vendor.",
            "url": "classes/App-Http-Controllers-API-V1-Vendor-VendorRegisterController.html#method_register"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Vendor\\VendorRegisterController\u003A\u003A\u0024vendorService",
            "name": "vendorService",
            "summary": "",
            "url": "classes/App-Http-Controllers-API-V1-Vendor-VendorRegisterController.html#property_vendorService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Auth\\UserLoginRequest",
            "name": "UserLoginRequest",
            "summary": "Class\u0020UserLoginRequest",
            "url": "classes/App-Http-Requests-Auth-UserLoginRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Auth\\UserLoginRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Auth-UserLoginRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Auth\\UserLoginRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Auth-UserLoginRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Auth\\UserRegisterRequest",
            "name": "UserRegisterRequest",
            "summary": "Class\u0020UserRegisterRequest",
            "url": "classes/App-Http-Requests-Auth-UserRegisterRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Auth\\UserRegisterRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Auth-UserRegisterRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Auth\\UserRegisterRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Auth-UserRegisterRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Auth\\UserRegisterRequest\u003A\u003Amessages\u0028\u0029",
            "name": "messages",
            "summary": "Get\u0020custom\u0020messages\u0020for\u0020validation\u0020errors.",
            "url": "classes/App-Http-Requests-Auth-UserRegisterRequest.html#method_messages"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Vendor\\VendorRegisterRequest",
            "name": "VendorRegisterRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Vendor-VendorRegisterRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Vendor\\VendorRegisterRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Vendor-VendorRegisterRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Vendor\\VendorRegisterRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Vendor-VendorRegisterRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ProfileResource",
            "name": "ProfileResource",
            "summary": "Class\u0020ProfileResource",
            "url": "classes/App-Http-Resources-ProfileResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\ProfileResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-ProfileResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UserResource",
            "name": "UserResource",
            "summary": "",
            "url": "classes/App-Http-Resources-UserResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UserResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-UserResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\VendorResource",
            "name": "VendorResource",
            "summary": "Class\u0020VendorResource",
            "url": "classes/App-Http-Resources-VendorResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\VendorResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-VendorResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Interfaces\\ProfileRepositoryInterface",
            "name": "ProfileRepositoryInterface",
            "summary": "Interface\u0020ProfileRepositoryInterface",
            "url": "classes/App-Interfaces-ProfileRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Interfaces\\ProfileRepositoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020profile.",
            "url": "classes/App-Interfaces-ProfileRepositoryInterface.html#method_create"
        },                {
            "fqsen": "\\App\\Interfaces\\ProfileRepositoryInterface\u003A\u003AfindByUserId\u0028\u0029",
            "name": "findByUserId",
            "summary": "Find\u0020a\u0020profile\u0020by\u0020user\u0020ID.",
            "url": "classes/App-Interfaces-ProfileRepositoryInterface.html#method_findByUserId"
        },                {
            "fqsen": "\\App\\Interfaces\\UserRepositoryInterface",
            "name": "UserRepositoryInterface",
            "summary": "Interface\u0020UserRepositoryInterface",
            "url": "classes/App-Interfaces-UserRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Interfaces\\UserRepositoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020user.",
            "url": "classes/App-Interfaces-UserRepositoryInterface.html#method_create"
        },                {
            "fqsen": "\\App\\Interfaces\\UserRepositoryInterface\u003A\u003AfindByEmail\u0028\u0029",
            "name": "findByEmail",
            "summary": "Find\u0020a\u0020user\u0020by\u0020email.",
            "url": "classes/App-Interfaces-UserRepositoryInterface.html#method_findByEmail"
        },                {
            "fqsen": "\\App\\Interfaces\\UserRepositoryInterface\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Find\u0020a\u0020user\u0020by\u0020ID.",
            "url": "classes/App-Interfaces-UserRepositoryInterface.html#method_findById"
        },                {
            "fqsen": "\\App\\Interfaces\\UserRepositoryInterface\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020a\u0020user\u0027s\u0020information.",
            "url": "classes/App-Interfaces-UserRepositoryInterface.html#method_update"
        },                {
            "fqsen": "\\App\\Interfaces\\UserRepositoryInterface\u003A\u003AupdateLoginStatus\u0028\u0029",
            "name": "updateLoginStatus",
            "summary": "Update\u0020a\u0020user\u0027s\u0020login\u0020status.",
            "url": "classes/App-Interfaces-UserRepositoryInterface.html#method_updateLoginStatus"
        },                {
            "fqsen": "\\App\\Interfaces\\VendorRepositoryInterface",
            "name": "VendorRepositoryInterface",
            "summary": "",
            "url": "classes/App-Interfaces-VendorRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Interfaces\\VendorRepositoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Interfaces-VendorRepositoryInterface.html#method_create"
        },                {
            "fqsen": "\\App\\Interfaces\\VendorRepositoryInterface\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "",
            "url": "classes/App-Interfaces-VendorRepositoryInterface.html#method_findById"
        },                {
            "fqsen": "\\App\\Interfaces\\VendorRepositoryInterface\u003A\u003AfindByUserId\u0028\u0029",
            "name": "findByUserId",
            "summary": "",
            "url": "classes/App-Interfaces-VendorRepositoryInterface.html#method_findByUserId"
        },                {
            "fqsen": "\\App\\Listeners\\SendLoginEmail",
            "name": "SendLoginEmail",
            "summary": "Class\u0020SendLoginEmail",
            "url": "classes/App-Listeners-SendLoginEmail.html"
        },                {
            "fqsen": "\\App\\Listeners\\SendLoginEmail\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020event.",
            "url": "classes/App-Listeners-SendLoginEmail.html#method_handle"
        },                {
            "fqsen": "\\App\\Livewire\\BaseComponent",
            "name": "BaseComponent",
            "summary": "",
            "url": "classes/App-Livewire-BaseComponent.html"
        },                {
            "fqsen": "\\App\\Livewire\\BaseComponent\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/App-Livewire-BaseComponent.html#method_render"
        },                {
            "fqsen": "\\App\\Livewire\\BaseComponent\u003A\u003A\u0024layout",
            "name": "layout",
            "summary": "",
            "url": "classes/App-Livewire-BaseComponent.html#property_layout"
        },                {
            "fqsen": "\\App\\Livewire\\HomePage",
            "name": "HomePage",
            "summary": "",
            "url": "classes/App-Livewire-HomePage.html"
        },                {
            "fqsen": "\\App\\Livewire\\HomePage\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/App-Livewire-HomePage.html#method_render"
        },                {
            "fqsen": "\\App\\Mail\\UserLoggedInNotification",
            "name": "UserLoggedInNotification",
            "summary": "Class\u0020UserLoggedInNotification",
            "url": "classes/App-Mail-UserLoggedInNotification.html"
        },                {
            "fqsen": "\\App\\Mail\\UserLoggedInNotification\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020message\u0020instance.",
            "url": "classes/App-Mail-UserLoggedInNotification.html#method___construct"
        },                {
            "fqsen": "\\App\\Mail\\UserLoggedInNotification\u003A\u003Aenvelope\u0028\u0029",
            "name": "envelope",
            "summary": "Get\u0020the\u0020message\u0020envelope.",
            "url": "classes/App-Mail-UserLoggedInNotification.html#method_envelope"
        },                {
            "fqsen": "\\App\\Mail\\UserLoggedInNotification\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "Get\u0020the\u0020message\u0020content\u0020definition.",
            "url": "classes/App-Mail-UserLoggedInNotification.html#method_content"
        },                {
            "fqsen": "\\App\\Mail\\UserLoggedInNotification\u003A\u003A\u0024event",
            "name": "event",
            "summary": "The\u0020user\u0020instance.",
            "url": "classes/App-Mail-UserLoggedInNotification.html#property_event"
        },                {
            "fqsen": "\\App\\Models\\Profile",
            "name": "Profile",
            "summary": "Class\u0020Profile",
            "url": "classes/App-Models-Profile.html"
        },                {
            "fqsen": "\\App\\Models\\Profile\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Get\u0020the\u0020user\u0020that\u0020owns\u0020the\u0020profile.",
            "url": "classes/App-Models-Profile.html#method_user"
        },                {
            "fqsen": "\\App\\Models\\Profile\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-Profile.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "Class\u0020User",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Acasts\u0028\u0029",
            "name": "casts",
            "summary": "Get\u0020the\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#method_casts"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003AhasRole\u0028\u0029",
            "name": "hasRole",
            "summary": "Check\u0020if\u0020the\u0020user\u0020has\u0020a\u0020specific\u0020role.",
            "url": "classes/App-Models-User.html#method_hasRole"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Avendor\u0028\u0029",
            "name": "vendor",
            "summary": "Get\u0020the\u0020vendor\u0020associated\u0020with\u0020the\u0020user.",
            "url": "classes/App-Models-User.html#method_vendor"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Aprofile\u0028\u0029",
            "name": "profile",
            "summary": "Get\u0020the\u0020profile\u0020associated\u0020with\u0020the\u0020user.",
            "url": "classes/App-Models-User.html#method_profile"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\Vendor",
            "name": "Vendor",
            "summary": "Class\u0020Vendor",
            "url": "classes/App-Models-Vendor.html"
        },                {
            "fqsen": "\\App\\Models\\Vendor\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Get\u0020the\u0020user\u0020that\u0020owns\u0020the\u0020vendor.",
            "url": "classes/App-Models-Vendor.html#method_user"
        },                {
            "fqsen": "\\App\\Models\\Vendor\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-Vendor.html#property_fillable"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Repositories\\ProfileRepository",
            "name": "ProfileRepository",
            "summary": "Class\u0020ProfileRepository",
            "url": "classes/App-Repositories-ProfileRepository.html"
        },                {
            "fqsen": "\\App\\Repositories\\ProfileRepository\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020profile\u0020record.",
            "url": "classes/App-Repositories-ProfileRepository.html#method_create"
        },                {
            "fqsen": "\\App\\Repositories\\ProfileRepository\u003A\u003AfindByUserId\u0028\u0029",
            "name": "findByUserId",
            "summary": "Find\u0020a\u0020profile\u0020by\u0020user\u0020ID.",
            "url": "classes/App-Repositories-ProfileRepository.html#method_findByUserId"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository",
            "name": "UserRepository",
            "summary": "Class\u0020UserRepository",
            "url": "classes/App-Repositories-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020user\u0020record.",
            "url": "classes/App-Repositories-UserRepository.html#method_create"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Find\u0020a\u0020user\u0020by\u0020their\u0020ID.",
            "url": "classes/App-Repositories-UserRepository.html#method_findById"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository\u003A\u003AfindByEmail\u0028\u0029",
            "name": "findByEmail",
            "summary": "Find\u0020a\u0020user\u0020by\u0020their\u0020email\u0020address.",
            "url": "classes/App-Repositories-UserRepository.html#method_findByEmail"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020a\u0020user\u0020record.",
            "url": "classes/App-Repositories-UserRepository.html#method_update"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository\u003A\u003AupdateLoginStatus\u0028\u0029",
            "name": "updateLoginStatus",
            "summary": "Update\u0020a\u0020user\u0027s\u0020login\u0020status.",
            "url": "classes/App-Repositories-UserRepository.html#method_updateLoginStatus"
        },                {
            "fqsen": "\\App\\Repositories\\VendorRepository",
            "name": "VendorRepository",
            "summary": "",
            "url": "classes/App-Repositories-VendorRepository.html"
        },                {
            "fqsen": "\\App\\Repositories\\VendorRepository\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Repositories-VendorRepository.html#method_create"
        },                {
            "fqsen": "\\App\\Repositories\\VendorRepository\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "",
            "url": "classes/App-Repositories-VendorRepository.html#method_findById"
        },                {
            "fqsen": "\\App\\Repositories\\VendorRepository\u003A\u003AfindByUserId\u0028\u0029",
            "name": "findByUserId",
            "summary": "",
            "url": "classes/App-Repositories-VendorRepository.html#method_findByUserId"
        },                {
            "fqsen": "\\App\\Service\\AuthService",
            "name": "AuthService",
            "summary": "Class\u0020AuthService",
            "url": "classes/App-Service-AuthService.html"
        },                {
            "fqsen": "\\App\\Service\\AuthService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "AuthService\u0020constructor.",
            "url": "classes/App-Service-AuthService.html#method___construct"
        },                {
            "fqsen": "\\App\\Service\\AuthService\u003A\u003AauthenticateUser\u0028\u0029",
            "name": "authenticateUser",
            "summary": "Authenticate\u0020the\u0020user.",
            "url": "classes/App-Service-AuthService.html#method_authenticateUser"
        },                {
            "fqsen": "\\App\\Service\\AuthService\u003A\u003AregisterUser\u0028\u0029",
            "name": "registerUser",
            "summary": "Register\u0020a\u0020new\u0020user\u0020and\u0020create\u0020a\u0020profile.",
            "url": "classes/App-Service-AuthService.html#method_registerUser"
        },                {
            "fqsen": "\\App\\Service\\AuthService\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/App-Service-AuthService.html#property_userRepository"
        },                {
            "fqsen": "\\App\\Service\\AuthService\u003A\u003A\u0024profileRepository",
            "name": "profileRepository",
            "summary": "",
            "url": "classes/App-Service-AuthService.html#property_profileRepository"
        },                {
            "fqsen": "\\App\\Service\\VendorService",
            "name": "VendorService",
            "summary": "",
            "url": "classes/App-Service-VendorService.html"
        },                {
            "fqsen": "\\App\\Service\\VendorService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Service-VendorService.html#method___construct"
        },                {
            "fqsen": "\\App\\Service\\VendorService\u003A\u003AregisterAsVendor\u0028\u0029",
            "name": "registerAsVendor",
            "summary": "",
            "url": "classes/App-Service-VendorService.html#method_registerAsVendor"
        },                {
            "fqsen": "\\App\\Service\\VendorService\u003A\u003A\u0024vendorRepository",
            "name": "vendorRepository",
            "summary": "",
            "url": "classes/App-Service-VendorService.html#property_vendorRepository"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Events",
            "name": "Events",
            "summary": "",
            "url": "namespaces/app-events.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/app-helpers.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "namespaces/app-http-controllers-api-v1-auth.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1",
            "name": "V1",
            "summary": "",
            "url": "namespaces/app-http-controllers-api-v1.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API",
            "name": "API",
            "summary": "",
            "url": "namespaces/app-http-controllers-api.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\API\\V1\\Vendor",
            "name": "Vendor",
            "summary": "",
            "url": "namespaces/app-http-controllers-api-v1-vendor.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "namespaces/app-http-requests-auth.html"
        },                {
            "fqsen": "\\App\\Http\\Requests",
            "name": "Requests",
            "summary": "",
            "url": "namespaces/app-http-requests.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Vendor",
            "name": "Vendor",
            "summary": "",
            "url": "namespaces/app-http-requests-vendor.html"
        },                {
            "fqsen": "\\App\\Http\\Resources",
            "name": "Resources",
            "summary": "",
            "url": "namespaces/app-http-resources.html"
        },                {
            "fqsen": "\\App\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/app-interfaces.html"
        },                {
            "fqsen": "\\App\\Listeners",
            "name": "Listeners",
            "summary": "",
            "url": "namespaces/app-listeners.html"
        },                {
            "fqsen": "\\App\\Livewire",
            "name": "Livewire",
            "summary": "",
            "url": "namespaces/app-livewire.html"
        },                {
            "fqsen": "\\App\\Mail",
            "name": "Mail",
            "summary": "",
            "url": "namespaces/app-mail.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\App\\Repositories",
            "name": "Repositories",
            "summary": "",
            "url": "namespaces/app-repositories.html"
        },                {
            "fqsen": "\\App\\Service",
            "name": "Service",
            "summary": "",
            "url": "namespaces/app-service.html"
        }            ]
);
